[package]
name = "teleprobe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["probe-rs", "probe-rs-rtt"]
client-only = []

[dependencies]
anyhow = "1.0.44"
base64 = "0.13.0"
bytes = "1.1.0"
clap = { version = "3.1.5", features = ["derive", "env"]}
defmt-decoder = { version = "0.3.0", features = [ "unstable" ]}
env_logger = "0.9.0"
jsonwebtoken = "7.2.0"
log = "0.4.14"
object = "0.27.1"
probe-rs = { version = "0.12.0", optional = true }
probe-rs-rtt = { version = "0.12.0", optional = true }
reqwest = { version = "0.11.6", features = ["json"]}
serde = "1.0.130"
serde_json = "1.0.68"
serde_yaml = "0.8.21"
tokio = { version = "1", features = ["full"] }
url = "2.2.2"
warp = "0.3"
parking_lot = "0.12"
